### ISSUE TITLE
Open-source checklist

### ISSUE THREAD

**Issue by lutangar** [dis-moi/.github#3]
> __How you write (and code) affects your brand, too!__
Throughout the life of your project, you’ll do a lot of writing: READMEs, tutorials, community documents, responding to issues, maybe even newsletters and mailing lists.
>
> Whether it’s official documentation or a casual email, your writing style is part of your project’s brand. Consider how you might come across to your audience and whether that is the tone you wish to convey.
https://opensource.guide/starting-a-project/#how-you-write-and-code-affects-your-brand-too

## Overall
- [ ] Implement [generic templates](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files) for all community files

> Idea: Create co-authored commit on the code of conduct and other important files to show everyone read and particpated in the contrusction of the document.
> https://docs.github.com/en/github/committing-changes-to-your-project/creating-a-commit-with-multiple-authors#creating-co-authored-commits-on-the-command-line

- [ ] Implement exemple labels to add to new project:
  - [ ] Complexity (T shirt size)
  - [ ] [Good first issue](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/encouraging-helpful-contributions-to-your-project-with-labels)

- [] Documentation websites
  - Each repositories could have its own documentation website
 > https://docsify.js.org/#/quickstart
 > https://docusaurus.io/

  - We could also craft to aggregate all documentation on one website 
  https://stackoverflow.com/questions/60363094/possible-to-publish-docusaurus-cross-repo-from-multiple-repositories-to-aggrega

## [Extension](https://github.com/dis-moi/extension/community)
  - README
  
  - Issues
    - [ ] The issue queue is up-to-date, with issues clearly organized and labeled 
  
  
  - [ ] Sentry up & running & useful
## [Backend](https://github.com/dis-moi/backend/community)
  - [ ] Pre-commit hook for CS
  - [ ] Check for strict typings
  - [ ] Sentry up & running & useful
## [Mobile](https://github.com/dis-moi/mobile_poc/community)
  - [ ] Sentry up & running & useful
## [Website](https://github.com/dis-moi/www.dismoi.io/community)
  - [ ] Sentry up & running & useful

**Comment by lutangar** [comment]
https://github.com/getsentry/.github
